JAVA-2559: Cast java.nio.ByteBuffer instances where necessary to java…
….nio.Buffer to avoid NoSuchMethodError when running on Java 6 to Java 8

The Java 9 ByteBuffer classes introduces overloaded methods with covariant return types for the following methods used by the driver:

* position
* limit
* flip
* clear

Without casting, exceptions like this are thrown when executing on Java 8 and lower:

    java.lang.NoSuchMethodError: java.nio.ByteBuffer.limit(I)Ljava/nio/ByteBuffer

This is because the generated byte code includes the static return type of the method, which is not found on Java 8 and lower because
the overloaded methods with covariant return types don't exist.